# Generated by Django 5.0.7 on 2024-08-01 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_alter_userpersona_count'),
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.user')),
            ],
        ),
    ]
