# Generated by Django 5.0.7 on 2024-08-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_recommendroute_delete_recommendplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendroute',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
