# Generated by Django 5.0.7 on 2024-08-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_recommendroute_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendroute',
            name='updated_at',
        ),
    ]
