# Generated by Django 5.0.7 on 2024-07-25 09:47

import diary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0005_picture_picture11_picture_picture12_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('picture1', models.ImageField(blank=True, null=True, upload_to=diary.models.user_directory_path)),
                ('picture2', models.ImageField(blank=True, null=True, upload_to=diary.models.user_directory_path)),
                ('picture3', models.ImageField(blank=True, null=True, upload_to=diary.models.user_directory_path)),
                ('picture4', models.ImageField(blank=True, null=True, upload_to=diary.models.user_directory_path)),
                ('picture5', models.ImageField(blank=True, null=True, upload_to=diary.models.user_directory_path)),
                ('picture6', models.ImageField(blank=True, null=True, upload_to=diary.models.user_directory_path)),
                ('picture7', models.ImageField(blank=True, null=True, upload_to=diary.models.user_directory_path)),
                ('picture8', models.ImageField(blank=True, null=True, upload_to=diary.models.user_directory_path)),
                ('picture9', models.ImageField(blank=True, null=True, upload_to=diary.models.user_directory_path)),
                ('picture10', models.ImageField(blank=True, null=True, upload_to=diary.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.userinfopersona')),
            ],
        ),
    ]
