# Generated by Django 5.0.7 on 2024-07-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripdiary',
            old_name='user',
            new_name='user_info_persona',
        ),
    ]
