# Generated by Django 5.0.7 on 2024-07-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_rename_user_tripdiary_user_info_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripdiary',
            old_name='content',
            new_name='answer1',
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='answer2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='answer3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='answer4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='answer5',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='answer6',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='answer7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='answer8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='question1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='question2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='question3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='question4',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='question5',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='question6',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='question7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='question8',
            field=models.TextField(blank=True, null=True),
        ),
    ]
