# Generated by Django 5.0.7 on 2024-07-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_rename_content_tripdiary_answer1_tripdiary_answer2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdiary',
            name='diary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
