# Generated by Django 5.0.7 on 2024-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_tripdiary_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdiary',
            name='answer10',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='answer9',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='question10',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdiary',
            name='question9',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripdiary',
            name='answer7',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tripdiary',
            name='answer8',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tripdiary',
            name='question7',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tripdiary',
            name='question8',
            field=models.TextField(),
        ),
    ]
