# Generated by Django 5.0.7 on 2024-08-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_remove_tripdiary_picture1_remove_tripdiary_picture10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdiary',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
