# Generated by Django 5.0.7 on 2024-08-01 14:08

import diary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_tripdiary_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdiary',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=diary.models.user_directory_path),
        ),
    ]
