# Generated by Django 5.0.7 on 2024-08-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_alter_tripdiary_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdiary',
            name='real_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
