# Generated by Django 5.0.7 on 2024-07-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='ei',
        ),
        migrations.RemoveField(
            model_name='city',
            name='ft',
        ),
        migrations.RemoveField(
            model_name='city',
            name='pj',
        ),
        migrations.RemoveField(
            model_name='city',
            name='sn',
        ),
    ]
