# Generated by Django 5.0.7 on 2024-07-21 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_remove_city_ei_remove_city_ft_remove_city_pj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersona',
            name='user_info_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.userinfopersona'),
        ),
    ]
