# Generated by Django 5.0.7 on 2024-07-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_userpersona_user_info_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='model',
            field=models.BooleanField(default=False),
        ),
    ]
