# Generated by Django 5.0.7 on 2024-07-24 14:28

import persona.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture11',
            field=models.ImageField(blank=True, null=True, upload_to=persona.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='picture',
            name='picture12',
            field=models.ImageField(blank=True, null=True, upload_to=persona.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='picture',
            name='picture13',
            field=models.ImageField(blank=True, null=True, upload_to=persona.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='picture',
            name='picture14',
            field=models.ImageField(blank=True, null=True, upload_to=persona.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='picture',
            name='picture15',
            field=models.ImageField(blank=True, null=True, upload_to=persona.models.user_directory_path),
        ),
    ]
